 # default.yaml
 log_level: debug
 lang: coffee #js You can set either coffee or js as your inline scripting language
 redact: ['a.b.c', 'a.b.*', 'req.headers'] #refer pino log redact features to know more about log redaction